name: Build Splicedd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install missing UI deps
        run: pnpm add @nextui-org/button

      - name: Build with Tauri
        run: pnpm tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Splicedd Installer
          path: src-tauri/target/release/bundle
